# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 03:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opconsole', '0005_auto_20170410_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employes',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='django_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
