# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opconsole', '0007_remove_employes_email'),
        ('opconsole', '0002_auto_20170411_1306'),
    ]

    operations = [
    ]
