# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opconsole', '0008_merge_20170411_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='zones',
            name='color',
            field=models.IntegerField(default=16711180),
        ),
    ]
