# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opconsole', '0010_auto_20170411_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zones',
            old_name='colors',
            new_name='color',
        ),
    ]
