# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opconsole', '0014_auto_20170412_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opconsole.Employes'),
        ),
    ]
