# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opconsole', '0017_timesheets'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='devKey',
            field=models.CharField(default='test', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='salt',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
