# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opconsole', '0014_device_timesheets'),
        ('opconsole', '0018_auto_20170413_2319'),
    ]

    operations = [
    ]
