# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 05:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opconsole', '0020_auto_20170501_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='initDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='device',
            name='salt',
            field=models.CharField(max_length=100),
        ),
    ]
