# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opconsole', '0021_auto_20170501_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheets',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tms', to='opconsole.Employes'),
        ),
        migrations.AlterField(
            model_name='timesheets',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='opconsole.Employes'),
        ),
    ]
