# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opconsole', '0022_auto_20170502_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='employes',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='salt',
            field=models.CharField(max_length=14),
        ),
    ]
