# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opconsole', '0023_auto_20170502_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='employes',
            name='enableDeviceCheck',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employes',
            name='enableGeoCheck',
            field=models.BooleanField(default=True),
        ),
    ]
