# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opconsole', '0024_auto_20170503_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employes',
            name='zones',
        ),
        migrations.AddField(
            model_name='device',
            name='zones',
            field=models.ManyToManyField(to='opconsole.Zones'),
        ),
    ]
