# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opconsole', '0027_device_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employes',
            name='enableDeviceCheck',
        ),
        migrations.RemoveField(
            model_name='employes',
            name='enableGeoCheck',
        ),
        migrations.AddField(
            model_name='device',
            name='enableDeviceCheck',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='device',
            name='enableGeoCheck',
            field=models.BooleanField(default=True),
        ),
    ]
