# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opconsole', '0029_timesheets_deletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheets',
            name='device',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tms', to='opconsole.Device'),
        ),
        migrations.AlterField(
            model_name='timesheets',
            name='status',
            field=models.CharField(choices=[(0, b'ACCEPTED'), (1, b'REFUSED_WRONG_TZ'), (2, b'REFUSED_DEV_DATA_MISMATCH'), (3, b'REFUSED_NOT_IN_ZONE'), (4, b'USER_DEACTIVATED'), (5, b'DEVICE_DEACTIVATED'), (6, b'WAITING_APPROVAL')], max_length=1),
        ),
    ]
