# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opconsole', '0030_auto_20170511_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheets',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tms', to='opconsole.Device'),
        ),
    ]
