# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 22:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opconsole', '0031_auto_20170511_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='employes',
            name='function',
            field=models.CharField(default='Employee', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employes',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employes',
            name='supervisor',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
