# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opconsole', '0033_auto_20170515_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employes',
            name='supervisor',
        ),
    ]
