# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opconsole', '0034_remove_employes_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employes',
            name='enable',
        ),
    ]
