# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opconsole', '0035_remove_employes_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='employes',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
