# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opconsole', '0037_employmenthistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmploymentHistory',
            new_name='ActivityRateHistory',
        ),
    ]
