# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opconsole', '0039_auto_20170515_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.DateTimeField()),
                ('to', models.DateTimeField()),
                ('type', models.IntegerField()),
                ('justification', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opconsole.Employes')),
            ],
        ),
    ]
