# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opconsole', '0040_absences'),
    ]

    operations = [
        migrations.AddField(
            model_name='employes',
            name='holidaysCount',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
