# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opconsole', '0041_employes_holidayscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employes',
            name='holidaysCount',
        ),
        migrations.AddField(
            model_name='employes',
            name='holidaysAnnualCount',
            field=models.IntegerField(default=20),
        ),
    ]
