# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opconsole', '0042_auto_20170524_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employes',
            name='holidaysAnnualCount',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
